on:
  push:
    branches: [
      master
    ]
  pull_request:
    branches: [
      master
    ]
  workflow_dispatch:  # Allows running this workflow manually from Actions tab


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    - name: Download and Cache the Interpreter
      id: hello 
      uses: metaeducation/ren-c-action@release

    - name: Output Where R3 Was Installed
      run: |
        echo "The path was ${{ steps.hello.outputs.path }}"

    - name: Demonstrate R3 is Now On Executable Path
      run: |
        r3 --do "print {Hello Path World}"

    - name: Cached Usage Test (shouldn't download again)
      uses: metaeducation/ren-c-action@release
      with:
        script: |
          print {This time, we run a script!}
          print {You can write multiple lines here...}

